[profile.default]
  evm_version = "cancun"
  ffi = true
  fs_permissions = [{ access = "read-write", path = ".forge-snapshots/" }]
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 200
  out = "out"
  solc_version = "0.8.24"
  src = "src"

  # [etherscan]

  # See more config options https://github.com/foundry-rs/foundry/tree/master/config
